artifact_location: /Users/abdulsalam/Documents/housing_app_fall25/notebooks/PASTE_MLFLOW_URI_HERE/0
creation_time: 1765837671650
experiment_id: '0'
last_update_time: 1765837671650
lifecycle_stage: active
name: Default
