artifact_uri: /Users/abdulsalam/Documents/housing_app_fall25/notebooks/PASTE_MLFLOW_URI_HERE/381628100968772676/6ab4b7bd6c9548429a6101c8f8a74d35/artifacts
end_time: 1765849633157
entry_point_name: ''
experiment_id: '381628100968772676'
lifecycle_stage: active
run_id: 6ab4b7bd6c9548429a6101c8f8a74d35
run_name: Exp5_GradientBoosting_PCA-False_Tuned-False
source_name: ''
source_type: 4
source_version: ''
start_time: 1765849632441
status: 3
tags: []
user_id: abdsalam25
