artifact_uri: /Users/abdulsalam/Documents/housing_app_fall25/notebooks/PASTE_MLFLOW_URI_HERE/381628100968772676/37b8dfd91a7746c0857b05d97a72bbc1/artifacts
end_time: 1765849640490
entry_point_name: ''
experiment_id: '381628100968772676'
lifecycle_stage: active
run_id: 37b8dfd91a7746c0857b05d97a72bbc1
run_name: Exp15_LightGBM_PCA-True_Tuned-False
source_name: ''
source_type: 4
source_version: ''
start_time: 1765849639038
status: 3
tags: []
user_id: abdsalam25
