artifact_uri: /Users/abdulsalam/Documents/housing_app_fall25/notebooks/PASTE_MLFLOW_URI_HERE/381628100968772676/86b644a9eecb40ac82fcbce6212a584a/artifacts
end_time: 1765849635445
entry_point_name: ''
experiment_id: '381628100968772676'
lifecycle_stage: active
run_id: 86b644a9eecb40ac82fcbce6212a584a
run_name: Exp10_XGBoost_PCA-False_Tuned-True
source_name: ''
source_type: 4
source_version: ''
start_time: 1765849635266
status: 3
tags: []
user_id: abdsalam25
