artifact_uri: /Users/abdulsalam/Documents/housing_app_fall25/notebooks/PASTE_MLFLOW_URI_HERE/381628100968772676/6016ba8a1d3e48e19f64e381177b1dc1/artifacts
end_time: 1765849637929
entry_point_name: ''
experiment_id: '381628100968772676'
lifecycle_stage: active
run_id: 6016ba8a1d3e48e19f64e381177b1dc1
run_name: Exp13_LightGBM_PCA-False_Tuned-False
source_name: ''
source_type: 4
source_version: ''
start_time: 1765849636166
status: 3
tags: []
user_id: abdsalam25
