artifact_location: /Users/abdulsalam/Documents/housing_app_fall25/notebooks/PASTE_MLFLOW_URI_HERE/381628100968772676
creation_time: 1765849632260
experiment_id: '381628100968772676'
last_update_time: 1765849632260
lifecycle_stage: active
name: Final_Project_Experiments
