artifact_uri: /Users/abdulsalam/Documents/housing_app_fall25/notebooks/PASTE_MLFLOW_URI_HERE/381628100968772676/b53e4cea98ce4fc0a84afb6363e6c838/artifacts
end_time: 1765849636164
entry_point_name: ''
experiment_id: '381628100968772676'
lifecycle_stage: active
run_id: b53e4cea98ce4fc0a84afb6363e6c838
run_name: Exp12_XGBoost_PCA-True_Tuned-True
source_name: ''
source_type: 4
source_version: ''
start_time: 1765849635997
status: 3
tags: []
user_id: abdsalam25
