artifact_uri: /Users/abdulsalam/Documents/housing_app_fall25/notebooks/PASTE_MLFLOW_URI_HERE/381628100968772676/96fd3ef0e3a348f7905b56d27cc4f661/artifacts
end_time: 1765849634705
entry_point_name: ''
experiment_id: '381628100968772676'
lifecycle_stage: active
run_id: 96fd3ef0e3a348f7905b56d27cc4f661
run_name: Exp8_GradientBoosting_PCA-True_Tuned-True
source_name: ''
source_type: 4
source_version: ''
start_time: 1765849634307
status: 3
tags: []
user_id: abdsalam25
