artifact_uri: /Users/abdulsalam/Documents/housing_app_fall25/notebooks/PASTE_MLFLOW_URI_HERE/381628100968772676/584fcc0a893f4cf397dd7c6bfcba768f/artifacts
end_time: 1765849632391
entry_point_name: ''
experiment_id: '381628100968772676'
lifecycle_stage: active
run_id: 584fcc0a893f4cf397dd7c6bfcba768f
run_name: Exp3_Ridge_PCA-True_Tuned-False
source_name: ''
source_type: 4
source_version: ''
start_time: 1765849632359
status: 3
tags: []
user_id: abdsalam25
