artifact_uri: /Users/abdulsalam/Documents/housing_app_fall25/notebooks/PASTE_MLFLOW_URI_HERE/381628100968772676/5bb623fd87ff42388f16bb3151287d0c/artifacts
end_time: 1765849641205
entry_point_name: ''
experiment_id: '381628100968772676'
lifecycle_stage: active
run_id: 5bb623fd87ff42388f16bb3151287d0c
run_name: Exp16_LightGBM_PCA-True_Tuned-True
source_name: ''
source_type: 4
source_version: ''
start_time: 1765849640492
status: 3
tags: []
user_id: abdsalam25
