artifact_uri: /Users/abdulsalam/Documents/housing_app_fall25/notebooks/PASTE_MLFLOW_URI_HERE/381628100968772676/603bae7c3d954d2098d71ef24f5d9a1a/artifacts
end_time: 1765849639036
entry_point_name: ''
experiment_id: '381628100968772676'
lifecycle_stage: active
run_id: 603bae7c3d954d2098d71ef24f5d9a1a
run_name: Exp14_LightGBM_PCA-False_Tuned-True
source_name: ''
source_type: 4
source_version: ''
start_time: 1765849637931
status: 3
tags: []
user_id: abdsalam25
