artifact_uri: /Users/abdulsalam/Documents/housing_app_fall25/notebooks/PASTE_MLFLOW_URI_HERE/818398674199534543/1a401f36a44b45f9b0fc787e828eeea2/artifacts
end_time: 1765837673473
entry_point_name: ''
experiment_id: '818398674199534543'
lifecycle_stage: active
run_id: 1a401f36a44b45f9b0fc787e828eeea2
run_name: powerful-crow-26
source_name: ''
source_type: 4
source_version: ''
start_time: 1765837671705
status: 3
tags: []
user_id: PASTE_USERNAME_HERE
