artifact_location: /Users/abdulsalam/Documents/housing_app_fall25/notebooks/PASTE_MLFLOW_URI_HERE/818398674199534543
creation_time: 1765837671654
experiment_id: '818398674199534543'
last_update_time: 1765837671654
lifecycle_stage: active
name: Churn_Model_Exp
