artifact_uri: /Users/abdulsalam/Documents/housing_app_fall25/notebooks/PASTE_MLFLOW_URI_HERE/381628100968772676/6033e35596064baf970aa6e9267fc25a/artifacts
end_time: 1765849635265
entry_point_name: ''
experiment_id: '381628100968772676'
lifecycle_stage: active
run_id: 6033e35596064baf970aa6e9267fc25a
run_name: Exp9_XGBoost_PCA-False_Tuned-False
source_name: ''
source_type: 4
source_version: ''
start_time: 1765849634707
status: 3
tags: []
user_id: abdsalam25
