artifact_uri: /Users/abdulsalam/Documents/housing_app_fall25/notebooks/PASTE_MLFLOW_URI_HERE/381628100968772676/7e2c177bf23144a4b30e6afeda9a416f/artifacts
end_time: 1765849632440
entry_point_name: ''
experiment_id: '381628100968772676'
lifecycle_stage: active
run_id: 7e2c177bf23144a4b30e6afeda9a416f
run_name: Exp4_Ridge_PCA-True_Tuned-True
source_name: ''
source_type: 4
source_version: ''
start_time: 1765849632392
status: 3
tags: []
user_id: abdsalam25
